"""empty message

Revision ID: 11617db62896
Revises: a730785c244f
Create Date: 2020-01-10 10:21:49.057094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11617db62896'
down_revision = 'a730785c244f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=200), nullable=True))
    op.drop_column('post', 'tittle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tittle', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
