"""empty message

Revision ID: 4c88a1bee064
Revises: 11617db62896
Create Date: 2020-01-10 18:54:43.663034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c88a1bee064'
down_revision = '11617db62896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=200), nullable=True))
    op.drop_column('post', 'tittle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tittle', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
