"""empty message

Revision ID: 75d3f2750742
Revises: 3616273d0cad
Create Date: 2020-01-09 15:39:45.141890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d3f2750742'
down_revision = '3616273d0cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tittle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('content', sa.VARCHAR(length=300), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
